services:
  # Backend API
  - type: web
    name: petland-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: petland-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REDIS_URL
        fromService:
          type: redis
          name: petland-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_URL
        value: "cloudinary://your-cloudinary-url"

  # Frontend
  - type: web
    name: petland-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://petland-backend.onrender.com
      - key: VITE_CLOUDINARY_URL
        value: "https://api.cloudinary.com/v1_1/yederpt/image/upload"

databases:
  - name: petland-db
    databaseName: petland
    user: petland_user
    plan: free

  - name: petland-redis
    plan: free 